name 'bs'
maintainer 'The Backscratchers'
maintainer_email 'leo@thebackscratchers.com'
description 'Manages The Backscratchers infrastructure'
long_description 'Manages infrastructure for The Backscratchers website on Amazon Web Services OpsWorks'
version '0.0.0'

depends 'apt', '~> 3.0.0'
depends 'application', '~> 5.1.0'
depends 'poise-ruby-build', '~> 1.0.1'
