# Override the normal deploy attributes
#
node[:deploy].each do |application, deploy|

  # Symlink additional files generated by Backscratchers configuration
  #
  normal[:deploy][application][:symlink_before_migrate]["config/secrets.yml"] = "config/secrets.yml"

end
