# Override the normal deploy attributes
#
node[:deploy].each do |application, deploy|

  # Symlink additional files generated by Backscratchers configuration
  #
  normal[:deploy][application][:symlink_before_migrate]["config/secrets.yml"] = "config/secrets.yml"
  normal[:deploy][application][:symlink_before_migrate]["config/s3_credentials.yml"] = "config/s3_credentials.yml"
  normal[:deploy][application][:symlink_before_migrate]["config/insightly.yml"] = "config/insightly.yml"
  normal[:deploy][application][:symlink_before_migrate]["config/xero.yml"] = "config/xero.yml"

end
